version: "3.1"
services:
  web:
    image: 127.0.0.1:5000/testeapp  
    build: 
      context: ./web
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    ports:
      - "80:80"
    networks:
      - frontend
networks:
  frontend:
