version: "3"
services:
  web:
    image: phptesteapp
    build:
      context: ./web
      dockerfile: Dockerfile    
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    ports:
      - "80:80"
    networks:
      - frontend
networks:
  frontend:
