version: "3.1"
services:
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    image: phptesteapp  
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    ports:
      - "80:80"
    networks:
      - frontend
networks:
  frontend:
